Add error for empty output file

diff --git a/tools/ebi_metagenomics_run_downloader/download_files b/tools/ebi_metagenomics_run_downloader/download_files
--- a/tools/ebi_metagenomics_run_downloader/download_files
+++ b/tools/ebi_metagenomics_run_downloader/download_files
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+set -e
+
 python_script=$1
 run_id=$2
 information_type=$3
@@ -12,8 +14,17 @@ run_link=$(python $python_script --run_id $run_id)
 run_link="$run_link/$information_type/$information_to_download"
 
 if [[ $chunk_type == 'multiple_chunks' ]]; then
-    echo "$run_link/chunks"
     chunk_nb=$(curl "$run_link/chunks")
+
+    if [[ "$chunk_nb" < 1 ]]; then
+        >&2 echo "-----"
+        >&2 echo "ERROR"
+        >&2 echo "-----"
+        >&2 echo "No data are found for this link:"
+        >&2 echo "$run_link/chunks"
+        >&2 echo "-----"
+        exit 6
+    fi
 
     for i in $(seq "$chunk_nb"); do
         curl "$run_link/chunks/$i" | gunzip >> $output_file
@@ -22,4 +33,12 @@ else
     curl "$run_link" >> $output_file
 fi
 
-
+if [ ! -s $output_file ]; then
+    >&2 echo "-----"
+    >&2 echo "ERROR"
+    >&2 echo "-----"
+    >&2 echo "The output file is empty probably because the following link is not working:"
+    >&2 echo "$run_link"
+    >&2 echo "-----"
+    exit 6
+fi
