Sync ci and pr GitHub workflows

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -39,7 +39,7 @@ jobs:
         echo "::set-output name=fork::${TMP:-$GALAXY_FORK}"
         TMP="${{ github.event.client_payload.slash_command.args.named.branch }}"
         echo "::set-output name=branch::${TMP:-$GALAXY_RELEASE}"
-    - name: Determine latest galaxy commit
+    - name: Determine latest commit in the Galaxy repo
       id: get-galaxy-sha
       run: echo "::set-output name=galaxy_head_sha::$(git ls-remote https://github.com/${{ steps.get-fork-branch.outputs.fork }}/galaxy refs/heads/${{ steps.get-fork-branch.outputs.branch }} | cut -f1)"
     - uses: actions/setup-python@v1
@@ -125,14 +125,14 @@ jobs:
     - name: Install Planemo
       run: pip install planemo
     - name: Planemo ci_find_tools, chunked
-      run: planemo ci_find_tools --chunk_count ${{ needs.setup.outputs.nchunks }} --chunk ${{ matrix.chunk  }} --exclude test_repositories --exclude packages --exclude deprecated --exclude_from .tt_skip --group_tools --output tool_list_chunk.txt
+      run: planemo ci_find_tools --chunk_count ${{ needs.setup.outputs.nchunks }} --chunk ${{ matrix.chunk }} --exclude test_repositories --exclude packages --exclude deprecated --exclude_from .tt_skip --group_tools --output tool_list_chunk.txt
     - name: Show tool list chunk
       run: cat tool_list_chunk.txt
     - name: Planemo test tools
       run: |
         mkdir json_output
         while read -r TOOL_GROUP; do
-            # Check if any of the lines in .tt_biocontainer_skip is a substring of $TOOL
+            # Check if any of the lines in .tt_biocontainer_skip is a substring of $TOOL_GROUP
             if echo $TOOL_GROUP | grep -qf .tt_biocontainer_skip; then
                 PLANEMO_OPTIONS=""
             else
@@ -155,9 +155,14 @@ jobs:
         mv tool_test_output.json tool_test_output.html upload/
     - uses: actions/upload-artifact@v2
       with:
-        name: 'Tool test output ${{ matrix.chunk  }}'
+        name: 'Tool test output ${{ matrix.chunk }}'
         path: upload
 
+  # - combine the results of the test chunks (which will never fail due
+  #   to `|| true`) and create a global test report as json and html which
+  #   is provided as artifact
+  # - check if any tool test actually failed (by lookup in the combined json)
+  #   and fail this step if this is the case
   combine_outputs:
     name: Combine chunked test results
     needs: [setup, test]
