bash improvements
Co-authored-by: Nicola Soranzo <nicola.soranzo@gmail.com>

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -150,10 +150,10 @@ jobs:
     - name: Check if each tool is in the list of repositories
       run: |
         set -e
-        while read -r DIR; do
-            dn=$(dirname $DIR);
-            if ! grep -lq $dn ../workflow_artifacts/changed_repos.list; then
-                >&2 echo "$DIR not in reository list: .shed.yml file missing"
+        while read -r TOOL; do
+            dn=$(dirname $TOOL);
+            if ! grep -q $dn ../workflow_artifacts/changed_repos.list; then
+                echo "$TOOL not in changed repository list: .shed.yml file missing" >&2
                 exit 1
             fi
         done < ../workflow_artifacts/changed_tools.list
@@ -309,7 +309,7 @@ jobs:
       run: |
         mkdir json_output/
         while read -r TOOLS; do
-           if grep -lqf .tt_biocontainer_skip <(echo $TOOLS); then
+           if grep -qf .tt_biocontainer_skip <(echo $TOOLS); then
                PLANEMO_OPTIONS=""
            else
                PLANEMO_OPTIONS="--biocontainers --no_dependency_resolution --no_conda_auto_init"
