group tools for planemo tesing
- simplifies the logic a bit since tools and data managers don't need to
be treated separately.
- check if every path in find_tools is in the output of find_repos, i.e.
check for missing .shed.yml

- all linters run now on the result of ci_find_repos
- tool testing uses ci_find_tools

as suggested here https://github.com/galaxyproject/tools-iuc/pull/3248#issuecomment-708993697

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -86,10 +86,16 @@ jobs:
       run: planemo ci_find_repos --changed_in_commit_range $COMMIT_RANGE --exclude packages --exclude deprecated --exclude_from .tt_skip --output changed_repositories.list
     - name: Show repo list
       run: cat changed_repositories.list
+    - name: Planemo ci_find_tools
+      run: planemo ci_find_tools --changed_in_commit_range $COMMIT_RANGE --exclude packages --exclude deprecated --exclude_from .tt_skip --output changed_tools.list
+    - name: Show tool list
+      run: cat changed_tools.list
     - uses: actions/upload-artifact@v2.0.1
       with:
         name: Workflow artifacts
-        path: changed_repositories.list
+        path: |
+          changed_repositories.list
+          changed_tools.list
 
   # Planemo lint the changed repositories
   lint:
@@ -129,6 +135,16 @@ jobs:
         while read -r DIR; do
             planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive "$DIR";
         done < ../workflow_artifacts/changed_repositories.list
+    - name: Check if each tool is in the list of repositories
+      run: |
+        set -e
+        while read -r DIR; do
+            dn=$(dirname $DIR);
+            if ! grep -lq $dn ../workflow_artifacts/changed_repos.list; then
+                >&2 echo "$DIR not in reository list: .shed.yml file missing"
+                exit 1
+            fi
+        done < ../workflow_artifacts/changed_tools.list
 
   # flake8 of Python scripts in the changed repositories
   flake8:
@@ -274,43 +290,24 @@ jobs:
     - name: Install Planemo
       run: pip install planemo
     - name: Planemo ci_find_tools
-      run: |
-        touch changed_repositories_chunk.list changed_tools_chunk.list
-        if [ -s ../workflow_artifacts/changed_repositories.list ]; then
-            if [ $(wc -l < ../workflow_artifacts/changed_repositories.list) -eq 1 ]; then
-                planemo ci_find_tools --chunk_count 4 --chunk ${{ matrix.chunk }} \
-                               --output changed_tools_chunk.list \
-                               $(cat ../workflow_artifacts/changed_repositories.list)
-            else
-                planemo ci_find_repos --chunk_count 4 --chunk ${{ matrix.chunk }} \
-                               --output changed_repositories_chunk.list \
-                               $(cat ../workflow_artifacts/changed_repositories.list)
-            fi
-        fi
-    - name: Show changed tools/repositories chunk list
-      run: cat changed_tools_chunk.list changed_repositories_chunk.list
+      run: planemo ci_find_tools --chunk_count 4 --chunk ${{ matrix.chunk }} --changed_in_commit_range $COMMIT_RANGE --exclude packages --exclude deprecated --exclude_from .tt_skip --output changed_tools_chunk.list
+    - name: Show tool list
+      run: cat changed_tools_chunk.list
     - name: Planemo test tools
       run: |
-        if grep -lqf .tt_biocontainer_skip changed_tools_chunk.list changed_repositories_chunk.list; then
-                PLANEMO_OPTIONS=""
-        else
-                PLANEMO_OPTIONS="--biocontainers --no_dependency_resolution --no_conda_auto_init"
-        fi
-        if [ -s changed_tools_chunk.list ]; then
-            PIP_QUIET=1 planemo test --database_connection postgresql://postgres:postgres@localhost:5432/galaxy $PLANEMO_OPTIONS --galaxy_source $GALAXY_REPO --galaxy_branch $GALAXY_RELEASE --galaxy_python_version ${{ matrix.python-version }} --test_output_json tool_test_output.json $(cat changed_tools_chunk.list) || true
-            docker system prune --all --force --volumes || true
-        elif [ -s changed_repositories_chunk.list ]; then
-            while read -r DIR; do
-                if [[ "$DIR" =~ ^data_managers.* ]]; then
-                    TESTPATH=$(planemo ci_find_tools "$DIR")
-                else
-                    TESTPATH="$DIR"
-                fi
-                PIP_QUIET=1 planemo test --database_connection postgresql://postgres:postgres@localhost:5432/galaxy $PLANEMO_OPTIONS --galaxy_source $GALAXY_REPO --galaxy_branch $GALAXY_RELEASE --galaxy_python_version ${{ matrix.python-version }} --test_output_json "$DIR"/tool_test_output.json "$TESTPATH" || true
-                docker system prune --all --force --volumes || true
-            done < changed_repositories_chunk.list
-        else
-            echo '{"tests":[]}' > tool_test_output.json
+        mkdir json_output/
+        while read -r TOOLS; do
+           if grep -lqf .tt_biocontainer_skip <(echo $TOOLS); then
+               PLANEMO_OPTIONS=""
+           else
+               PLANEMO_OPTIONS="--biocontainers --no_dependency_resolution --no_conda_auto_init"
+           fi
+           json=$(mktemp -u -p json_output --suff .json)
+           PIP_QUIET=1 planemo test --database_connection postgresql://postgres:postgres@localhost:5432/galaxy --no_conda_auto_init --galaxy_branch $GALAXY_RELEASE --biocontainers --no_dependency_resolution --galaxy_python_version ${{ matrix.python-version }} --test_output_json $json $TOOLS || true
+           docker system prune --all --force --volumes || true
+        done < changed_tools_chunk.list
+        if [ ! -s changed_tools_chunk.list ]; then
+            echo '{"tests":[]}' > $(mktemp -u -p json_output --suff .json)
         fi
     - name: Merge tool_test_output.json files
       run: find . -name tool_test_output.json -exec sh -c 'planemo merge_test_reports "$@" tool_test_output.json' sh {} +
